# Generated by Django 2.2 on 2019-06-04 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meet_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
