# Generated by Django 2.2 on 2019-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_meeting_meet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='purpose',
            field=models.CharField(max_length=255),
        ),
    ]
