# Generated by Django 2.2 on 2019-06-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190604_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
