# Generated by Django 2.2 on 2019-06-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190608_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
